#!/usr/bin/env python3
"""Generate the model's report appendices (markdown) from the YAML source
and the engine's own results: a derived artifact, regenerated, never
committed.

Tables: risk metrics (value, and uncertainty band when sampled),
initiating events, parameters, basic events (failure model with units,
the engine's point probability after CCF expansion, distribution,
provenance), CCF groups (factors and the engine's per-multiplicity
probabilities), house events, event trees (functional events and the
sequence table with frequencies), fault-tree gates (formulas). Every
number is copied from the model or from the results JSON, never
recomputed, and every provenance block verbatim.

Usage: appendix.py <model-dir> <results.json> <out.md> [--revision REV]
  results.json is what ci/quantify.py writes (point, or with --samples, or
  truncated with --truncated: then metrics and sequence frequencies are
  bounds [lower, upper], rounded outward, FR-42).
"""
import argparse
import glob
import json
import os
import sys

import yaml

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import bounds  # noqa: E402


def esc(x) -> str:
    """A markdown table cell: pipes escaped, newlines flattened."""
    return " ".join(str(x).split()).replace("|", "\\|")


def num(x) -> str:
    return f"{x:.4e}" if isinstance(x, float) else str(x)


def qty(q, params) -> str:
    if isinstance(q, dict) and "param" in q:
        p = params.get(q["param"], {})
        return f"{q['param']} ({num(float(p.get('value')))} {p.get('unit', '')})"
    if isinstance(q, dict):
        return f"{num(float(q['value']))} {q.get('unit', '')}".strip()
    return esc(q)


def dist(u) -> str:
    if not u:
        return "—"
    d = u.get("distribution")
    rest = ", ".join(f"{k} {v}" for k, v in sorted(u.items()) if k != "distribution")
    return f"{d} ({rest})"


def formula_text(f) -> str:
    if isinstance(f, str):
        return f
    (op, a), = f.items()
    if op == "not":
        return f"NOT({formula_text(a)})"
    if op == "atleast":
        return f"ATLEAST {a['k']} OF ({', '.join(formula_text(x) for x in a['of'])})"
    return f"{op.upper()}({', '.join(formula_text(x) for x in a)})"


def table(header, rows) -> list:
    out = ["| " + " | ".join(header) + " |", "|" + "---|" * len(header)]
    out += ["| " + " | ".join(esc(c) for c in r) + " |" for r in rows]
    return out + [""]


def load_all(model_dir, sub, key):
    out = {}
    for p in sorted(glob.glob(os.path.join(model_dir, sub, "*.yaml"))):
        out.update((yaml.safe_load(open(p)) or {}).get(key, {}) or {})
    return out


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("model_dir")
    ap.add_argument("results")
    ap.add_argument("out")
    ap.add_argument("--revision", help="git revision to print in the header")
    a = ap.parse_args()
    md = a.model_dir
    manifest = yaml.safe_load(open(os.path.join(md, "model.yaml")))
    params = (yaml.safe_load(open(os.path.join(md, "parameters.yaml"))) or {}).get(
        "parameters") or {}
    house = (yaml.safe_load(open(os.path.join(md, "house-events.yaml"))) or {}).get(
        "house_events") or {}
    cpath = os.path.join(md, "ccf-groups.yaml")
    ccf = ((yaml.safe_load(open(cpath)) or {}).get("ccf_groups") or {}
           if os.path.exists(cpath) else {})
    bes = load_all(md, "basic-events", "basic_events")
    fts = load_all(md, "fault-trees", "fault_trees")
    ets = {}
    for p in sorted(glob.glob(os.path.join(md, "event-trees", "*.yaml"))):
        t = yaml.safe_load(open(p))["event_tree"]
        ets[t["id"]] = t
    results = json.load(open(a.results))
    probs = {}
    for r in results.values():
        probs.update(r.get("basic_event_probabilities", {}))
    prov = lambda e: ((e or {}).get("provenance") or {})

    m = manifest.get("model", {})
    out = [f"# Model appendices — {esc(m.get('id', ''))}", "",
           f"{esc(m.get('name', ''))}. Schema {manifest.get('schema_version', '?')}"
           + (f", revision `{a.revision}`" if a.revision else "") + ". Generated by "
           "`ci/appendix.py` from the model and the engine's results; do not edit.", ""]

    # risk metrics
    bands = {}
    totals = bounds.metric_totals(results)
    bounded = bounds.any_truncated(results)
    for et in results.values():
        for mt in et.get("metrics", []):
            u = mt.get("uncertainty")
            if u and len(results) == 1:
                bands[mt["id"]] = u
    out += ["## A.1 Risk metrics", ""]
    if bounded:
        out += [f"Truncated quantification ({bounds.method_note(results)}): metric "
                f"values and sequence frequencies are rigorous bounds [lower, upper].", ""]
    out += table(["metric", "label", "end states",
                  "bounds (/yr)" if bounded else "point value (/yr)", "mean [5%, 95%] (/yr)"],
                 [[r["id"], r.get("label", ""), ", ".join(r.get("end_states", [])),
                   bounds.fmt_interval(*totals.get(r["id"], (0.0, 0.0)), bounded),
                   (f"{num(bands[r['id']]['mean'])} [{num(bands[r['id']]['p05'])}, "
                    f"{num(bands[r['id']]['p95'])}]") if r["id"] in bands else "—"]
                  for r in m.get("risk_metrics", [])])

    out += ["## A.2 Initiating events", ""]
    out += table(["event tree", "initiating event", "label", "frequency", "distribution",
                  "source", "justification"],
                 [[tid, t["initiating_event"]["id"], t["initiating_event"].get("label", ""),
                   qty(t["initiating_event"]["frequency"], params),
                   dist(t["initiating_event"]["frequency"].get("uncertainty")),
                   prov(t["initiating_event"]).get("source", ""),
                   prov(t["initiating_event"]).get("justification", "")]
                  for tid, t in sorted(ets.items()) if "initiating_event" in t]
                 + [[tid, "— (transfer-only)", "", "", "", "", ""]
                    for tid, t in sorted(ets.items()) if "initiating_event" not in t])

    out += ["## A.3 Parameters", ""]
    out += table(["parameter", "label", "value", "distribution", "source", "justification"],
                 [[pid, p.get("label", ""), f"{num(float(p['value']))} {p.get('unit', '')}",
                   dist(p.get("uncertainty")), prov(p).get("source", ""),
                   prov(p).get("justification", "")] for pid, p in sorted(params.items())])

    member_of = {m_: gid for gid, g in ccf.items() for m_ in g.get("members", [])}

    def be_dist(bid, b, fm):
        """Where the event's sampled uncertainty comes from, if anywhere."""
        if bid in member_of:
            grp = ccf[member_of[bid]]
            tp = grp.get("total_probability") or {}
            src = (params.get(tp["param"], {}).get("uncertainty")
                   if isinstance(tp, dict) and "param" in tp else
                   (tp.get("uncertainty") if isinstance(tp, dict) else None))
            parts = [f"total ({dist(src)})"] if src else []
            fu = grp.get("factor_uncertainty")
            if fu:
                parts.append(f"factors (Dirichlet, concentration {fu.get('concentration')})")
            return (f"via {member_of[bid]} " + " and ".join(parts) if parts
                    else f"— ({member_of[bid]} member)")
        if b.get("uncertainty"):
            return dist(b["uncertainty"])
        parts = []
        for k, v in fm.items():
            if not isinstance(v, dict):
                continue
            if "param" in v and params.get(v["param"], {}).get("uncertainty"):
                parts.append(f"{k} via {v['param']} ({dist(params[v['param']]['uncertainty'])})")
            elif v.get("uncertainty"):
                parts.append(f"{k}: {dist(v['uncertainty'])}")
        return "; ".join(parts) or "—"

    out += ["## A.4 Basic events", "",
            "Point probability: the engine's value, after failure-model conversion and "
            "CCF expansion (a CCF member shows its independent part Q₁).", ""]
    rows = []
    for bid, b in sorted(bes.items()):
        fm = b.get("failure_model") or {}
        inputs = "; ".join(f"{k} {qty(v, params)}" for k, v in fm.items() if k != "type")
        rows.append([bid, b.get("label", ""), b.get("system", ""),
                     f"{fm.get('type', '')}: {inputs}",
                     num(probs[bid]) if bid in probs else "not quantified",
                     be_dist(bid, b, fm), prov(b).get("source", ""),
                     prov(b).get("justification", "")])
    out += table(["basic event", "label", "system", "failure model", "point probability",
                  "distribution", "source", "justification"], rows)

    if ccf:
        out += ["## A.5 Common-cause failure groups", ""]
        rows = []
        for gid, g in sorted(ccf.items()):
            n = len(g.get("members", []))
            qk = []
            for k in range(2, n + 1):
                ex = next((v for e, v in sorted(probs.items())
                           if e.startswith(f"BE-{gid}-") and len(e[len(f'BE-{gid}-'):].split('-')) == k),
                          None)
                qk.append(f"Q{k} {num(ex)}" if ex is not None else f"Q{k} —")
            q1 = probs.get(g["members"][0]) if g.get("members") else None
            testing = ("n/a (beta-factor)" if g.get("model") == "beta-factor"
                       else g.get("testing", "staggered"))
            fu = g.get("factor_uncertainty")
            factors = ", ".join(f"{k} {v}" for k, v in sorted((g.get("factors") or {}).items()))
            if fu:
                factors += f" (Dirichlet, concentration {fu.get('concentration')})"
            rows.append([gid, g.get("model", ""), testing, ", ".join(g.get("members", [])),
                         qty(g.get("total_probability"), params),
                         factors,
                         "; ".join([f"Q1 {num(q1)}" if q1 is not None else "Q1 —"] + qk),
                         prov(g).get("source", ""), prov(g).get("justification", "")])
        out += table(["group", "model", "testing", "members", "total probability Qt",
                      "factors", "engine Q_k (per combination event)", "source",
                      "justification"], rows)

    out += ["## A.6 House events", ""]
    out += table(["house event", "label", "default", "source", "justification"],
                 [[hid, h.get("label", ""), str(h.get("default")).lower(),
                   prov(h).get("source", ""), prov(h).get("justification", "")]
                  for hid, h in sorted(house.items())])

    out += ["## A.7 Event trees", ""]
    for tid, t in sorted(ets.items()):
        out += [f"### {tid} — {esc(t.get('label', ''))}", ""]
        out += table(["functional event", "label", "top gate"],
                     [[fe, f.get("label", ""), f.get("top_gate", "")]
                      for fe, f in t["functional_events"].items()])
        res = results.get(tid, {})
        freq = {s["id"]: bounds.fmt_interval(*bounds.seq_interval(s), bounds.is_truncated(res))
                for s in res.get("sequences", [])}
        order = list(t["functional_events"])
        short = {"success": "S", "failure": "F", "bypassed": "–"}
        rows = []
        for sid, sq in sorted(t["sequences"].items()):
            rows.append([sid, " ".join(short[sq["path"][fe]] for fe in order),
                         sq.get("end_state", ""),
                         f"→ {sq['transfer']}" if sq.get("transfer") else "",
                         freq[sid] if sid in freq else "not quantified"])
        out += [f"Path columns: {', '.join(order)} (S success, F failure, – bypassed).", ""]
        out += table(["sequence", "path", "end state", "transfer", "frequency (/yr)"], rows)

    out += ["## A.8 Fault-tree gates", ""]
    rows = []
    for fid, f in sorted(fts.items()):
        for gid, g in sorted((f.get("gates") or {}).items()):
            rows.append([fid, gid, g.get("label", ""), formula_text(g.get("formula"))])
    out += table(["fault tree", "gate", "label", "formula"], rows)

    with open(a.out, "w") as fh:
        fh.write("\n".join(out))
    print(f"appendix written to {a.out}: {len(params)} parameters, {len(bes)} basic "
          f"events, {len(ccf)} CCF groups, {len(house)} house events, "
          f"{sum(len(t['sequences']) for t in ets.values())} sequences, "
          f"{len(rows)} gates")
    return 0


if __name__ == "__main__":
    sys.exit(main())
