#!/usr/bin/env python3
"""Expand authoring templates into the flat model (FR-41).

The flat YAML under model/ is the source of truth — what is reviewed,
diffed, validated and quantified. Templates only help write it: a
component type states its failure modes once (failure model, optional
event-level uncertainty, provenance), and an instance file lists the
components of that type that one model file holds. `expand` writes those
files in full, literally; `--check` (CI) fails unless every generated file
is exactly what its template produces today — so a template change shows
up in review as the literal change of every event it touches, and a hand
edit of a generated file cannot slip through.

Templates live outside the model directory (default ./templates):

  component_types:                        # any templates/*.yaml
    CT-ECC-MDP:
      label: "ECCS motor-driven pump"     # descriptive, not emitted
      failure_modes:
        FTS:
          label: "fails to start on demand"
          failure_model: {type: probability, value: {param: PAR-ECC-PMP-FTS}}
          provenance: {source: "...", justification: "..."}
        FTR: {...}

  output: basic-events/ecc-pumps.yaml     # an instance file
  header: |                               # optional; copied as comments
    Basic events for the ECCS pumps.
  components:
    ECC-PMP-A:
      type: CT-ECC-MDP
      label: "ECCS pump A"
      system: ECC                         # optional, copied
      component: PMP-A                    # optional, copied
      overrides:                          # optional, per failure mode;
        FTR:                              # provenance required with any
          failure_model: {...}            # data override
          provenance: {...}

Each component yields `BE-<component>-<mode>` for every failure mode of its
type, in the type's order, components in the file's order, labelled
"<component label> <mode label>", with the fields in the house order
(label, system, component, failure_mode, failure_model, uncertainty,
provenance). A generated file starts with a GENERATED header naming its
template. `expand` refuses to overwrite a hand-written file, and reports
(never deletes) generated files whose template is gone.

Usage: expand_templates.py [--templates DIR] [--model DIR] [--check]
"""
from __future__ import annotations

import argparse
import difflib
import os
import re
import sys

import yaml

GENERATED = "# GENERATED by `canopy expand` from "
ID_PART = re.compile(r"^[A-Z0-9]+(-[A-Z0-9]+)*$")
MODE = re.compile(r"^[A-Z0-9]+$")
TYPE_ID = re.compile(r"^CT-[A-Z0-9]+(-[A-Z0-9]+)*$")
PLAIN = re.compile(r"^[A-Za-z0-9_][A-Za-z0-9_.\-]*$")
RESERVED = {"true", "false", "yes", "no", "on", "off", "null", "y", "n", "~"}


class TemplateError(Exception):
    pass


# ---------------------------------------------------------------- emitter
def fmt_float(x: float) -> str:
    """The number as analysts write it, read back exactly: scientific
    notation with the fewest mantissa digits that round-trip for
    magnitudes below 1e-2 or from 1e4 (`1.2e-3`, `3.0e-5`, `1.5e+4`),
    else the shortest round-trip decimal (`0.9787`, `24.0`). Always with a
    dot and a signed exponent: PyYAML's YAML 1.1 resolver reads `3e-05` or
    `1.5e4` as strings."""
    x = float(x)
    if x != x or x in (float("inf"), float("-inf")):
        raise TemplateError(f"non-finite number {x}")
    if x != 0.0 and (abs(x) < 1e-2 or abs(x) >= 1e4):
        for p in range(0, 18):
            t = f"{x:.{p}e}"
            if float(t) == x:
                break
        m, e = t.split("e")
        if "." not in m:
            m += ".0"
        sign, digits = e[0], e[1:].lstrip("0") or "0"
        return f"{m}e{sign}{digits}"
    s = repr(x)
    return s if "." in s else s + ".0"


def fmt_scalar(v, quote=False) -> str:
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, int):
        return str(v)
    if isinstance(v, float):
        return fmt_float(v)
    if v is None:
        return "null"
    s = str(v)
    if (not quote and PLAIN.match(s) and s.lower() not in RESERVED
            and not re.match(r"^[-+.]?[0-9]", s)):
        return s
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n") + '"'


QUOTED_KEYS = {"label", "source", "justification"}
FLOW_KEYS = {"value", "unit", "param"}


def emit(obj, indent: int, out: list, key_hint: str = "") -> None:
    pad = " " * indent
    for k, v in obj.items():
        if isinstance(v, dict):
            if v and set(v) <= FLOW_KEYS and not any(isinstance(x, (dict, list)) for x in v.values()):
                inner = ", ".join(f"{kk}: {fmt_scalar(vv)}" for kk, vv in v.items())
                out.append(f"{pad}{k}: {{{inner}}}")
            else:
                out.append(f"{pad}{k}:")
                emit(v, indent + 2, out, k)
        elif isinstance(v, list):
            out.append(f"{pad}{k}:")
            for item in v:
                if isinstance(item, (dict, list)):
                    raise TemplateError(f"nested list items are not supported under {k}")
                out.append(f"{pad}  - {fmt_scalar(item)}")
        else:
            out.append(f"{pad}{k}: {fmt_scalar(v, quote=k in QUOTED_KEYS)}")


def render(template_rel: str, header: str, events: dict) -> str:
    lines = [f"{GENERATED}{template_rel}; do not edit —",
             "# edit the template, run `python ci/canopy.py expand`; CI checks this file."]
    if header:
        lines.append("#")
        lines += [("# " + h).rstrip() for h in header.rstrip("\n").split("\n")]
    lines.append("basic_events:")
    for eid, body in events.items():
        lines.append("")
        lines.append(f"  {eid}:")
        emit(body, 4, lines)
    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------- expansion
def load_templates(tdir: str):
    types, instances = {}, []
    if not os.path.isdir(tdir):
        return types, instances
    for name in sorted(os.listdir(tdir)):
        path = os.path.join(tdir, name)
        if name.startswith(".") or not os.path.isfile(path):
            continue
        if not name.endswith(".yaml"):
            raise TemplateError(f"{path}: only .yaml files belong in the templates directory")
        doc = yaml.safe_load(open(path)) or {}
        if not isinstance(doc, dict):
            raise TemplateError(f"{path}: must be a mapping")
        unknown = set(doc) - {"component_types", "output", "header", "components"}
        if unknown:
            raise TemplateError(f"{path}: unknown key(s) {sorted(unknown)}")
        for tid, t in (doc.get("component_types") or {}).items():
            if not TYPE_ID.match(str(tid)):
                raise TemplateError(f"{path}: component type id {tid!r} must look like CT-NAME")
            if tid in types:
                raise TemplateError(f"{path}: component type {tid} defined twice")
            if not isinstance(t, dict) or set(t) - {"label", "failure_modes"}:
                raise TemplateError(f"{path}: {tid}: allowed keys are label, failure_modes")
            modes = t.get("failure_modes") or {}
            if not modes:
                raise TemplateError(f"{path}: {tid}: no failure_modes")
            for mid, m in modes.items():
                if not MODE.match(str(mid)):
                    raise TemplateError(f"{path}: {tid}: failure mode {mid!r} must be A-Z/0-9")
                extra = set(m) - {"label", "failure_model", "uncertainty", "provenance"}
                missing = {"label", "failure_model", "provenance"} - set(m)
                if extra or missing:
                    raise TemplateError(f"{path}: {tid}/{mid}: unknown {sorted(extra)} "
                                        f"missing {sorted(missing)}")
            types[tid] = (path, t)
        if "output" in doc or "components" in doc:
            if "output" not in doc or "components" not in doc:
                raise TemplateError(f"{path}: an instance file needs both output and components")
            instances.append((path, doc))
    return types, instances


def expand(tdir: str, model_dir: str) -> dict:
    """{absolute output path: rendered text} for every instance file."""
    types, instances = load_templates(tdir)
    outputs, owner_of_id = {}, {}
    for path, doc in instances:
        out_rel = doc["output"]
        if (not isinstance(out_rel, str) or not re.match(r"^basic-events/[a-z0-9][a-z0-9._-]*\.yaml$", out_rel)):
            raise TemplateError(f"{path}: output must be basic-events/<name>.yaml, got {out_rel!r}")
        target = os.path.join(model_dir, out_rel)
        if target in outputs:
            raise TemplateError(f"{path}: output {out_rel} is also generated by another template")
        events = {}
        for cid, c in (doc["components"] or {}).items():
            where = f"{path}: {cid}"
            if not ID_PART.match(str(cid)):
                raise TemplateError(f"{where}: component id must be A-Z/0-9 words joined by '-'")
            if not isinstance(c, dict) or set(c) - {"type", "label", "system", "component", "overrides"}:
                raise TemplateError(f"{where}: allowed keys are type, label, system, component, overrides")
            if c.get("type") not in types:
                raise TemplateError(f"{where}: unknown component type {c.get('type')!r}")
            if not c.get("label"):
                raise TemplateError(f"{where}: label required")
            _, t = types[c["type"]]
            overrides = c.get("overrides") or {}
            for mid, o in overrides.items():
                if mid not in t["failure_modes"]:
                    raise TemplateError(f"{where}: override of unknown failure mode {mid}")
                if set(o) - {"label", "failure_model", "uncertainty", "provenance"}:
                    raise TemplateError(f"{where}/{mid}: override keys are label, failure_model, "
                                        f"uncertainty, provenance")
                if (("failure_model" in o or "uncertainty" in o) and "provenance" not in o):
                    raise TemplateError(f"{where}/{mid}: an override of data needs its own provenance")
            for mid, m in t["failure_modes"].items():
                m = {**m, **(overrides.get(mid) or {})}
                eid = f"BE-{cid}-{mid}"
                if eid in owner_of_id:
                    raise TemplateError(f"{where}: {eid} is also generated by {owner_of_id[eid]}")
                owner_of_id[eid] = path
                body = {"label": f"{c['label']} {m['label']}"}
                for k in ("system", "component"):
                    if c.get(k) is not None:
                        body[k] = c[k]
                body["failure_mode"] = mid
                body["failure_model"] = m["failure_model"]
                if m.get("uncertainty") is not None:
                    body["uncertainty"] = m["uncertainty"]
                body["provenance"] = m["provenance"]
                events[eid] = body
        rel_tpl = os.path.relpath(path, os.path.dirname(os.path.abspath(model_dir)))
        text = render(rel_tpl.replace(os.sep, "/"), doc.get("header") or "", events)
        # self-check: the text must read back as exactly the intended data
        back = yaml.safe_load(text)
        if back != {"basic_events": events}:
            raise TemplateError(f"{path}: internal: rendered YAML does not read back as the "
                                f"intended data (please report)")
        outputs[target] = text
    # hand-written events must not collide with generated ones
    bdir = os.path.join(model_dir, "basic-events")
    for name in sorted(os.listdir(bdir)) if os.path.isdir(bdir) else []:
        p = os.path.join(bdir, name)
        if p in outputs or not name.endswith(".yaml"):
            continue
        if open(p).readline().startswith(GENERATED):
            continue
        for eid in ((yaml.safe_load(open(p)) or {}).get("basic_events") or {}):
            if eid in owner_of_id:
                raise TemplateError(f"{p}: {eid} is hand-written but also generated by "
                                    f"{owner_of_id[eid]}")
    return outputs


def generated_files(model_dir: str) -> list:
    """Files under the model that carry the GENERATED header."""
    out = []
    for root, _, files in os.walk(model_dir):
        for f in sorted(files):
            p = os.path.join(root, f)
            if f.endswith(".yaml") and open(p).readline().startswith(GENERATED):
                out.append(p)
    return sorted(out)


def main() -> int:
    ap = argparse.ArgumentParser(description="Expand templates into the flat model.")
    ap.add_argument("--templates", default="templates")
    ap.add_argument("--model", default="model")
    ap.add_argument("--check", action="store_true",
                    help="write nothing; fail unless every generated file is up to date")
    a = ap.parse_args()
    try:
        outputs = expand(a.templates, a.model)
    except TemplateError as e:
        print(f"ERROR: {e}", file=sys.stderr)
        return 1
    problems = []
    for p in generated_files(a.model):
        if p not in outputs:
            problems.append(f"{p}: generated file without a template (delete it, or restore "
                            f"its template)")
    changed = []
    for p, text in outputs.items():
        exists = os.path.exists(p)
        cur = open(p).read() if exists else None
        if exists and not cur.startswith(GENERATED):
            problems.append(f"{p}: hand-written file; refusing to overwrite it with generated "
                            f"content (move its entities, or choose another output)")
            continue
        if cur != text:
            changed.append(p)
            if a.check:
                diff = "".join(list(difflib.unified_diff(
                    (cur or "").splitlines(True), text.splitlines(True),
                    fromfile=f"{p} (committed)", tofile=f"{p} (from templates)"))[:40])
                problems.append(f"{p}: {'missing' if cur is None else 'differs from its templates'}"
                                f" (run `python ci/canopy.py expand`)\n{diff}")
    if problems:
        for pr in problems:
            print(f"ERROR: {pr}", file=sys.stderr)
        return 1
    if a.check:
        print(f"templates: {len(outputs)} generated file(s) up to date")
        return 0
    for p in changed:
        with open(p, "w") as f:
            f.write(outputs[p])
    print(f"templates: {len(outputs)} generated file(s), {len(changed)} written"
          + ("".join(f"\n  {os.path.relpath(p)}" for p in changed)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
