#!/usr/bin/env python3
"""Tests for the template expander (FR-41): ci/expand_templates.py and
`canopy expand`.

  * Golden output: a fixture type and instance file expand to exactly the
    expected text (header, field order, flow-style quantities, quoting,
    event-level uncertainty, an override with its own provenance).
  * Numbers: 2,000 random floats over 600 orders of magnitude, plus edge
    values, are written so that YAML reads them back as the identical
    float, in analyst notation.
  * End to end: the expanded fixture validates and (when the engine is
    built) quantifies to the hand-computed value.
  * --check: clean passes; a hand edit, a missing file, a stale file after
    a template change, an orphaned generated file and a stripped header
    each fail, naming the file; expand then repairs the first three.
  * Refusals: overwriting a hand-written file, a hand-written event that is
    also generated, two templates for one output, an unknown type, a data
    override without provenance, an output outside basic-events/, unknown
    keys, a duplicate type, a bad component id.
  * Idempotent and deterministic (byte-identical under three hash seeds);
    the demo's templates are up to date; `canopy expand` = the script.

Usage: python ci/test_expand.py [--engine PATH]
"""
import argparse
import json
import math
import os
import random
import shutil
import subprocess
import sys
import tempfile

import yaml

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, HERE)
import expand_templates as et  # noqa: E402

PROV = {"source": "fixture source", "justification": "fixture justification"}

TYPES = """component_types:
  CT-VALVE:
    label: "motor-operated valve"
    failure_modes:
      FTO:
        label: "fails to open"
        failure_model:
          type: probability
          value: {value: 2.0e-3, unit: per_demand}
        uncertainty: {distribution: lognormal, error_factor: 3.0}
        provenance: {source: "type source", justification: "type justification"}
      PLG:
        label: "plugged"
        failure_model:
          type: rate-mission
          rate: {value: 5.0e-7, unit: per_hour}
          mission_time: {value: 24.0, unit: hour}
        provenance: {source: "type source", justification: "type justification"}
"""

INSTANCES = """output: basic-events/valves.yaml
header: |
  Valves of the fixture.
  Second header line.
components:
  SYS-VLV-A: {type: CT-VALVE, label: "System valve A", system: SYS, component: VLV-A}
  SYS-VLV-B:
    type: CT-VALVE
    label: "System valve B"
    overrides:
      PLG:
        failure_model:
          type: rate-mission
          rate: {value: 1.5e-6, unit: per_hour}
          mission_time: {value: 24.0, unit: hour}
        provenance: {source: "plant-specific", justification: "valve B history"}
"""

GOLDEN = """# GENERATED by `canopy expand` from templates/valves.yaml; do not edit —
# edit the template, run `python ci/canopy.py expand`; CI checks this file.
#
# Valves of the fixture.
# Second header line.
basic_events:

  BE-SYS-VLV-A-FTO:
    label: "System valve A fails to open"
    system: SYS
    component: VLV-A
    failure_mode: FTO
    failure_model:
      type: probability
      value: {value: 2.0e-3, unit: per_demand}
    uncertainty:
      distribution: lognormal
      error_factor: 3.0
    provenance:
      source: "type source"
      justification: "type justification"

  BE-SYS-VLV-A-PLG:
    label: "System valve A plugged"
    system: SYS
    component: VLV-A
    failure_mode: PLG
    failure_model:
      type: rate-mission
      rate: {value: 5.0e-7, unit: per_hour}
      mission_time: {value: 24.0, unit: hour}
    provenance:
      source: "type source"
      justification: "type justification"

  BE-SYS-VLV-B-FTO:
    label: "System valve B fails to open"
    failure_mode: FTO
    failure_model:
      type: probability
      value: {value: 2.0e-3, unit: per_demand}
    uncertainty:
      distribution: lognormal
      error_factor: 3.0
    provenance:
      source: "type source"
      justification: "type justification"

  BE-SYS-VLV-B-PLG:
    label: "System valve B plugged"
    failure_mode: PLG
    failure_model:
      type: rate-mission
      rate: {value: 1.5e-6, unit: per_hour}
      mission_time: {value: 24.0, unit: hour}
    provenance:
      source: "plant-specific"
      justification: "valve B history"
"""


def read(p):
    return open(p).read() if os.path.exists(p) else ""


def make_repo(tmp):
    """A model (with a fault tree over the generated events) and templates."""
    root = os.path.join(tmp, "repo")
    m, t = os.path.join(root, "model"), os.path.join(root, "templates")
    for d in ("basic-events", "fault-trees"):
        os.makedirs(os.path.join(m, d))
    os.makedirs(t)
    dump = lambda p, o: open(os.path.join(m, p), "w").write(yaml.safe_dump(o, sort_keys=False))
    dump("model.yaml", {"schema_version": "0.1.0",
                        "model": {"id": "EXPAND-TEST", "name": "expander fixture", "risk_metrics": []},
                        "includes": {"parameters": ["parameters.yaml"],
                                     "basic_events": ["basic-events/*.yaml"],
                                     "fault_trees": ["fault-trees/*.yaml"],
                                     "house_events": ["house-events.yaml"]}})
    dump("parameters.yaml", {"parameters": {}})
    dump("house-events.yaml", {"house_events": {}})
    dump("basic-events/other.yaml", {"basic_events": {"BE-HAND": {
        "label": "hand-written event", "provenance": PROV,
        "failure_model": {"type": "probability", "value": {"value": 0.1, "unit": "per_demand"}}}}})
    dump("fault-trees/ft.yaml", {"fault_trees": {"FT-V": {"label": "both valves fail to open",
        "top_gate": "GT-TOP", "gates": {"GT-TOP": {"label": "top gate",
            "formula": {"and": ["BE-SYS-VLV-A-FTO", "BE-SYS-VLV-B-FTO"]}}}}}})
    open(os.path.join(t, "types.yaml"), "w").write(TYPES)
    open(os.path.join(t, "valves.yaml"), "w").write(INSTANCES)
    return root, m, t


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--engine", default=os.environ.get(
        "CANOPY_BIN", os.path.join(ROOT, "engine/target/release/canopy")))
    a = ap.parse_args()
    failures = []

    def check(cond, msg):
        (print(f"  ok  {msg}") if cond else failures.append(msg))

    def expand(m, t, *extra, env=None):
        return subprocess.run([sys.executable, os.path.join(HERE, "expand_templates.py"),
                               "--model", m, "--templates", t, *extra],
                              capture_output=True, text=True, env={**os.environ, **(env or {})})

    # numbers
    rnd = random.Random(20260929)
    vals = [10 ** rnd.uniform(-300, 300) * rnd.choice([1, -1]) for _ in range(2000)]
    vals += [0.0, 1.0, 24.0, 0.05, 0.9787, 1e-2, 9.999e-3, 1e4, 9999.0, 5e-324, 1.7976931348623157e308]
    bad = [x for x in vals if yaml.safe_load(et.fmt_float(x)) != x
           or not isinstance(yaml.safe_load(et.fmt_float(x)), float)]
    check(not bad, f"{len(vals)} floats read back identically ({bad[:3]})")
    check([et.fmt_float(x) for x in (1.2e-3, 3e-5, 6e-3, 1.5e4, 0.9787, 24.0)]
          == ["1.2e-3", "3.0e-5", "6.0e-3", "1.5e+4", "0.9787", "24.0"],
          "analyst notation: 1.2e-3, 3.0e-5, 6.0e-3, 1.5e+4, 0.9787, 24.0")

    tmp = tempfile.mkdtemp(prefix="psa-expand-")
    try:
        root, m, t = make_repo(tmp)
        r = expand(m, t)
        out = os.path.join(m, "basic-events", "valves.yaml")
        text = read(out)
        check(r.returncode == 0 and text == GOLDEN, "golden output, byte for byte"
              + ("" if text == GOLDEN else "\n" + "".join(__import__("difflib").unified_diff(
                  GOLDEN.splitlines(True), text.splitlines(True)))[:1500]))
        v = subprocess.run([sys.executable, os.path.join(HERE, "validate.py"), m,
                            os.path.join(ROOT, "schema", "psa-model.schema.json")],
                           capture_output=True, text=True)
        check(v.returncode == 0, f"expanded model validates {v.stdout[-300:]}")
        if os.path.exists(a.engine):
            e = subprocess.run([a.engine, m, "FT-V", "--json", "--prob-only"],
                               capture_output=True, text=True)
            p = json.loads(e.stdout)["probability"] if e.returncode == 0 else None
            check(p is not None and math.isclose(p, 2.0e-3 ** 2, rel_tol=1e-12),
                  f"engine quantifies the expanded model: P(top) {p} = (2.0e-3)^2")
        else:
            print("  --  engine not built: end-to-end quantification skipped")
        check(expand(m, t, "--check").returncode == 0, "--check: up to date")
        r2 = expand(m, t)
        check(r2.returncode == 0 and "0 written" in r2.stdout, "idempotent: a second expand writes nothing")
        outs = []
        for seed in ("0", "1", "2"):
            if os.path.exists(out):
                os.remove(out)
            expand(m, t, env={"PYTHONHASHSEED": seed})
            outs.append(read(out))
        check(outs[0] == outs[1] == outs[2] == GOLDEN, "byte-identical under three hash seeds")

        # --check failures, and repair
        open(out, "a").write("\n# a hand edit\n")
        r = expand(m, t, "--check")
        check(r.returncode != 0 and "valves.yaml: differs from its templates" in r.stderr
              and "+# a hand edit" not in r.stderr and "-# a hand edit" in r.stderr,
              "--check: a hand edit of a generated file fails, with the diff")
        expand(m, t)
        os.remove(out)
        r = expand(m, t, "--check")
        check(r.returncode != 0 and "valves.yaml: missing" in r.stderr, "--check: a missing generated file fails")
        expand(m, t)
        open(os.path.join(t, "types.yaml"), "w").write(TYPES.replace("value: 2.0e-3", "value: 2.5e-3"))
        r = expand(m, t, "--check")
        check(r.returncode != 0 and "+      value: {value: 2.5e-3, unit: per_demand}" in r.stderr,
              "--check: a template change leaves the model stale, shown literally")
        r = expand(m, t)
        new = read(out)
        check(r.returncode == 0 and new.count("value: {value: 2.5e-3") == 2
              and expand(m, t, "--check").returncode == 0,
              "expand writes the change into every instance (2 events), then --check passes")
        open(os.path.join(t, "types.yaml"), "w").write(TYPES)
        expand(m, t)
        open(os.path.join(m, "basic-events", "old-valves.yaml"), "w").write(read(out) or GOLDEN)
        r = expand(m, t, "--check")
        check(r.returncode != 0 and "old-valves.yaml: generated file without a template" in r.stderr,
              "--check: an orphaned generated file fails")
        os.remove(os.path.join(m, "basic-events", "old-valves.yaml"))
        open(out, "w").write(GOLDEN.split("\n", 2)[2])      # header stripped
        r = expand(m, t)
        check(r.returncode != 0 and "hand-written file; refusing to overwrite" in r.stderr,
              "expand refuses to overwrite a file without the GENERATED header")
        open(out, "w").write(GOLDEN)

        # refusals
        def refused(files, frag, msg):
            d = tempfile.mkdtemp(dir=tmp)
            tt = os.path.join(d, "templates")
            os.makedirs(tt)
            mm = os.path.join(d, "model")
            shutil.copytree(m, mm)
            for name, body in files.items():
                open(os.path.join(tt, name), "w").write(body)
            r = expand(mm, tt)
            check(r.returncode != 0 and frag in r.stderr, f"refused: {msg} ({r.stderr.strip()[:90]})")
        refused({"types.yaml": TYPES, "valves.yaml": INSTANCES,
                 "again.yaml": INSTANCES.replace("SYS-VLV-A", "SYS-VLV-C").replace("SYS-VLV-B", "SYS-VLV-D")},
                "is also generated by another template", "two templates for one output")
        refused({"types.yaml": TYPES, "valves.yaml": INSTANCES.replace("type: CT-VALVE\n", "type: CT-NOPE\n")},
                "unknown component type 'CT-NOPE'", "an unknown type")
        refused({"types.yaml": TYPES, "valves.yaml": INSTANCES.replace(
            '        provenance: {source: "plant-specific", justification: "valve B history"}\n', "")},
                "an override of data needs its own provenance", "a data override without provenance")
        refused({"types.yaml": TYPES, "valves.yaml": INSTANCES.replace(
            "output: basic-events/valves.yaml", "output: ../elsewhere.yaml")},
                "output must be basic-events/<name>.yaml", "an output outside basic-events/")
        refused({"types.yaml": TYPES + "colour: red\n", "valves.yaml": INSTANCES},
                "unknown key(s) ['colour']", "an unknown top-level key")
        refused({"types.yaml": TYPES, "more.yaml": TYPES, "valves.yaml": INSTANCES},
                "component type CT-VALVE defined twice", "a duplicate type")
        refused({"types.yaml": TYPES, "valves.yaml": INSTANCES.replace("SYS-VLV-A:", "sys_vlv_a:")},
                "component id must be A-Z/0-9 words", "a bad component id")
        # a hand-written event that the templates also generate
        d = tempfile.mkdtemp(dir=tmp)
        shutil.copytree(m, os.path.join(d, "model"))
        shutil.copytree(t, os.path.join(d, "templates"))
        hp = os.path.join(d, "model", "basic-events", "other.yaml")
        doc = yaml.safe_load(open(hp))
        doc["basic_events"]["BE-SYS-VLV-A-FTO"] = doc["basic_events"]["BE-HAND"]
        yaml.safe_dump(doc, open(hp, "w"))
        r = expand(os.path.join(d, "model"), os.path.join(d, "templates"))
        check(r.returncode != 0 and "BE-SYS-VLV-A-FTO is hand-written but also generated" in r.stderr,
              "refused: a hand-written event that is also generated")
    finally:
        shutil.rmtree(tmp, ignore_errors=True)

    # the demo, and the CLI wrapper
    r = subprocess.run([sys.executable, os.path.join(HERE, "canopy.py"), "expand", "--check"],
                       capture_output=True, text=True, cwd=ROOT)
    s = subprocess.run([sys.executable, os.path.join(HERE, "expand_templates.py"), "--check"],
                       capture_output=True, text=True, cwd=ROOT)
    check(r.returncode == s.returncode == 0 and r.stdout == s.stdout and "up to date" in r.stdout,
          f"demo templates up to date; canopy expand = the script ({r.stdout.strip()})")

    if failures:
        for f in failures:
            print("FAIL:", f)
        return 1
    print("expand: all checks passed")
    return 0


if __name__ == "__main__":
    sys.exit(main())
